config/routes.rb
CarrierwaveDirectExample::Application.routes.draw do
  root :to => 'users#new'
  resources :users, :only => [:new, :create, :show]
  resource :avatar, :only => :new
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def new
    @uploader = User.new.avatar
    @uploader.success_action_redirect = new_user_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new(params)
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      Resque.enqueue(AvatarProcessor, @user.id, @user.key)
      redirect_to @user, notice: 'User was successfully created. Waiting for Avatar to be processed. Refresh at will'
    else
      render action: "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/avatars/new.html.erb
<%= direct_upload_form_for @uploader do |f| %>
  <%= f.file_field :avatar %>
  <%= f.submit "Upload Directly!" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarrierwaveDirectExample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% unless @user.has_avatar_upload? %>
    <%= link_to "Upload Avatar", new_avatar_path %>
  <% end %>

  <%= f.hidden_field :key %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag(@user.avatar_url) if @user.avatar? %>

<%= link_to 'New', new_user_path %>